name: Docker Image CI

on:
  push:
    branches: [ "main", devops-2 ]
  pull_request:
    branches: [ "main", devops-2 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file /day1/web/Dockerfile --tag web:$(date +%s)
